### ISSUE TITLE
test.py example is broken

### ISSUE THREAD

**Issue by sandyjmacdonald** [pimoroni/bme280-python#1]
`from bme280 import _bme280, CHIP_ID` fails to import `_bme280`. The fix is to instantiate the BME280 class and then access `_bme280` through that.

**Comment by Neex101** [comment]
Still down

**Comment by Gadgetoid** [comment]
Obsolete test, code, have "fixed" it accordingly. Thanks both!

**Comment by Neex101** [comment]
lolz - there is no spoon ;-)
