### ISSUE TITLE
Correct links on PyPi from https://pypi.org/project/pimoroni-bme280/

### ISSUE THREAD

**Issue by iohe** [pimoroni/bme280-python#10]
Hi Team,
    Multiple links from url point to bme680:
    Github, and related section Statistics.
    Sorry if this is not the best place to raise it.
Thank you!

**Comment by Gadgetoid** [comment]
Good catch! Thank you. Should be fixed in the next release.

**Comment by Gadgetoid** [comment]
I think these are all fixed now! Thanks again.
