### ISSUE TITLE
bme280

### ISSUE THREAD

**Issue by Johnalanj** [pimoroni/bme280-python#14]
please could somone guide me though the procedure on running the python programm all-values.py from the sample programs
bit new to the pi and what sudo etc amd what program i use to run to work the bme280

help gladly taken

**Comment by Gadgetoid** [comment]
I know I'm probably a day late and a dollar short here, but for anyone else who finds themselves here. These are rough instructions for a Pi 4/5:

Enable i2c:

```
sudo raspi-config nonint do_i2c 0
```

Check if i2c enabled and device connected:

```
sudo i2cdetect -y 1
```

(Should see `0x76` or `0x77` in the list of devices.)

Clone this repository:

```
git clone https://github.com/pimoroni/bme280-python
```

Use the installer script:

```
cd bme280-python
./install.sh
```

Answer "Y" to copy examples, then:

```
cd ~/Pimoroni/pimoroni-bme280
python3 all-values.py
```
