### ISSUE TITLE
Breakout board BME280

### ISSUE THREAD

**Issue by viveknath93** [pimoroni/bme280-python#15]
Hi Team,

I have a basic **question**.
Do we need to externally connect pull up resistors to establish a I2C communication ?
I see the break out board already having some SMD along with sensor and Diodes..
Are the terminals output points already having the pullup resistors ?
I am using a NXPk66F dev board.

**Comment by Gadgetoid** [comment]
All of our breakout boards are populated with 10k pull-up resistors Looks like bme280 has a little 4 resistor array for this- that component with "103" on it is "10" + three zeros, or "10,000" Ohms.

**Comment by viveknath93** [comment]
Thank you for the information
