### ISSUE TITLE
ValueError: Invalid format specifier when running allvalues.py

### ISSUE THREAD

**Issue by liamsanchez** [pimoroni/bme280-python#21]
installed the PIMORONI BME280 breakout on pins 1, 3, 5, 7, 9, on my RaspberryPI-4 however - when I run the allvalues.py example i get the following error:

Ctrl+C to exit
Traceback (most recent call last):
  File "/home/pi/BME280 test.py", line 19, in <module>
    print('{:05.2f}*C {:05.2f}hPa {:05:2f}%'.format(temperature, pressure, humidity))
ValueError: Invalid format specifier

**Comment by Gadgetoid** [comment]
Whoops indeed “:05:2f” is wrong; that should be “:05.2f” for five digits and two decimal places.
